name: CI for Billing service

on:
  pull_request:
    branches:
      - main
    paths:
      - 'microservices/billing-service/**'
      - '.github/workflows/ci-billing.yaml'

env:
  INFRA_REPO_URL: somnathbm/hospital-hms-infra

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/billing-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: pylint ./app --fail-under 5

      - name: Unit tests
        run: pytest ./app/tests

  build:
    runs-on: ubuntu-latest
    needs: [test]
    defaults:
      run:
        working-directory: microservices/billing-service

    steps:
      - uses: actions/checkout@v4

      - name: Build & push image
        id: build
        run: |
          IMAGE_REPO_NAME=somnathbm/hospital-hms-billing-service
          IMAGE_TAG=dev-sha-${{ github.sha }}
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $IMAGE_REPO_NAME:$IMAGE_TAG
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
  
  update_infra_repo:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.INFRA_REPO_URL }}
          token: ${{ secrets.GH_PAT }}
          ref: main
          fetch-depth: 0

      - name: Update image tag
        run: |
          # Set line endings correctly
          git config --global core.autocrlf input

          # Always on main first
          git checkout main
          git pull

          # Checkout new feature branch first
          git checkout -b update-billing-${{ github.sha }}

          # Modify the value file
          # sed -i "s/image: .*/image: ${{ env.IMAGE_TAG }}/" kustomize/overlays/dev/billing/billing-values.yaml
          sed -i "s/image: .*/image: ${{ env.IMAGE_TAG }}/" kustomize/overlays/dev/billing/billing-patch.yaml

          # Set the user name and email
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Commit the changes
          # git add kustomize/overlays/dev/billing/billing-values.yaml
          git add kustomize/overlays/dev/billing/billing-patch.yaml
          git commit -m "chore: update billing service image tag to ${{ env.IMAGE_TAG }}"
          git push -u origin update-billing-${{ github.sha }}

      # - name: Create new PR to infra repo
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GH_PAT }}
      #     base: main
      #     commit-message: "Updated billing svc image tag"
      #     title: "Updated billing image tag to ${{ env.IMAGE_TAG }}"
      #     body: "This PR updates billing service image tag"
      #     branch: update-billing-${{ github.sha }}
      # - name: Create new PR to infra repo
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GH_PAT }}
      #     base: main
      #     commit-message: "Updated billing svc image tag"
      #     title: "Updated billing image tag to ${{ env.IMAGE_TAG }}"
      #     body: "This PR updates billing service image tag"
      #     branch: update-billing-${{ github.sha }}