name: CI for Billing service

on:
  pull_request:
    branches:
      - main
    paths:
      - 'microservices/billing-service/**'
      - '.github/workflows/ci-billing.yaml'

env:
  INFRA_REPO_URL: somnathbm/hospital-hms-infra

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/billing-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Lint
        run: pylint ./app --fail-under 5

      - name: Unit tests
        run: pytest ./app/tests

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v4

      - name: Build & push image
        id: build
        run: |
          IMAGE_REPO_NAME=somnathbm/hospital-hms-billing-service
          IMAGE_TAG=dev-sha-${{ github.sha }} >> "$GITHUB_OUTPUT"
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $IMAGE_REPO_NAME:$IMAGE_TAG
    outputs:
      image_tag: ${{ steps.build.outputs.IMAGE_TAG }}
  
  update_infra_repo:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      IMAGE_TAG: ${{ needs.test_build.outputs.image_tag }}
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.INFRA_REPO_URL }}
          token: ${{ secrets.GH_PAT }}

      - name: Update image tag
        run: |
          cd overlays/dev
          sed -i "s/tag: .*/tag: ${{ env.IMAGE_TAG }}/" billing-values.yaml

          # set the user name and email
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # checkout new branch and commit to it
          git checkout -b update-billing-${{ github.sha }}
          git add billing-values.yaml
          git commit -m "chore: update billing service image tag to ${{ env.IMAGE_TAG }}"
          git push -u origin update-billing-${{ github.sha }}

      - name: Create new PR to infra repo
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.GH_PAT }}
          base: main
          commit-message: "Updated billing svc image tag"
          title: "Updated billing image tag to ${{ env.IMAGE_TAG }}"
          body: "This PR updates billing service image tag"
          branch: update-billing-${{ github.sha }}