name: CI for OPD Service

on:
  pull_request:
    branches:
      - main
    paths:
      - 'microservices/opd-service/**'
      - '.github/workflows/ci-opd.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/opd-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Lint
        run: go fmt ./internal/service/

      - name: Unit Tests
        run: go test ./internal/service

      - name: Build & Push Docker image
        run: |
          IMAGE_REPO_NAME=somnathbm/hospital-hms-opd-service
          IMAGE_TAG=sha-${{ github.sha }}
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $IMAGE_REPO_NAME:$IMAGE_TAG

  update_infra_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: somnathbm/hospital-hms-infra
          token: ${{ secrets.GH_PAT }}
          path: infra

      - name: Update image tag
        run: |
          cd overlays/dev
          sed -i "s/tag: .*/tag: dev-sha-${{ github.sha }}" opd-values.yaml

          # set the user name
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # checkout new branch and commit to it
          git checkout -b update-opd-${{ github.sha }}
          git add overlays/dev/opd-values.yaml
          git commit -m "chore: update OPD image tag to sha-${{ github.sha }}"
          git push origin update-opd-${{ github.sha }}

      - name: Create PR to infra repo
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          path: infra
          commit-message: "chore: update OPD image tag"
          title: "chore: update OPD image tag to sha-${{ github.sha }}"
          body: "This PR updates the OPD service image tag so that ArgoCD can pickup the new version"
          branch: update-opd-${{ github.sha }}