name: CI for OPD Service

on:
  pull_request:
    branches:
      - main
    paths:
      - 'microservices/opd-service/**'
      - '.github/workflows/ci-opd.yaml'

jobs:
  test_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/opd-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'microservices/opd-service/go.mod'
          cache-dependency-path: 'microservices/opd-service/go.sum'

      - name: Lint
        run: go fmt ./internal/service/

      - name: Unit Tests
        run: go test ./internal/service

      - name: Build & Push Docker image
        id: build
        run: |
          IMAGE_PATH=somnathbm/hospital-hms-opd-service:dev-sha-${{ github.sha }}
          echo "image_path=$IMAGE_PATH" >> $GITHUB_OUTPUT
          docker build -t $IMAGE_PATH .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $IMAGE_PATH
    outputs:
      image_path: ${{ steps.build.outputs.image_path }}

  update_infra_repo:
    runs-on: ubuntu-latest
    needs: [test_build]

    env:
      IMAGE_TAG: ${{ needs.test_build.outputs.image_path }}
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: somnathbm/hospital-hms-infra
          token: ${{ secrets.GH_PAT }}
          ref: main
          fetch-depth: 0

      - name: Update image tag
        run: |
          # Set line endings correctly
          git config --global core.autocrlf input

          # Always on main first
          git checkout main
          git pull

          # Checkout new feature branch first
          git checkout -b update-opd-${{ github.sha }}

          # Modify the value file
          # sed -i "s/tag: .*/tag: ${{ env.IMAGE_PATH }}/" kustomize/overlays/dev/opd/opd-values.yaml
          sed -i "s/image: .*/image: ${{ env.IMAGE_PATH }}/" kustomize/overlays/dev/opd/opd-patch.yaml

          # Set the user name
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Commit the changes
          # git add kustomize/overlays/dev/opd/opd-values.yaml
          git add kustomize/overlays/dev/opd/opd-patch.yaml
          git commit -m "chore: update OPD image tag to ${{ env.IMAGE_PATH }}"
          git push -u origin update-opd-${{ github.sha }}

      # - name: Create PR to infra repo
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GH_PAT }}
      #     base: main
      #     commit-message: "chore: update OPD image tag"
      #     title: "chore: update OPD image tag to ${{ env.IMAGE_TAG }}"
      #     body: "This PR updates the OPD service image tag so that ArgoCD can pickup the new version"
      #     branch: update-opd-${{ github.sha }}